FROM node:current-alpine AS base

FROM base AS deps
WORKDIR /app

COPY frontend/package.json frontend/package-lock.json* ./

RUN npm ci

FROM base AS BUILDER
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY ./frontend .

RUN npm run build

FROM base as RUNNER
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]